/* Auto-generated by genmsg_cpp for file /home/matt/myrospackages/robotunicorn225b/project2/gradient_planner/msg/GPCostmapM.msg */
#ifndef GRADIENT_PLANNER_MESSAGE_GPCOSTMAPM_H
#define GRADIENT_PLANNER_MESSAGE_GPCOSTMAPM_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "roslib/Header.h"

namespace gradient_planner
{
template <class ContainerAllocator>
struct GPCostmapM_ : public ros::Message
{
  typedef GPCostmapM_<ContainerAllocator> Type;

  GPCostmapM_()
  : header()
  , name()
  , rows(0)
  , cols(0)
  , data()
  {
  }

  GPCostmapM_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , name(_alloc)
  , rows(0)
  , cols(0)
  , data(_alloc)
  {
  }

  typedef  ::roslib::Header_<ContainerAllocator>  _header_type;
   ::roslib::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef int32_t _rows_type;
  int32_t rows;

  typedef int32_t _cols_type;
  int32_t cols;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  data;


  ROSCPP_DEPRECATED uint32_t get_data_size() const { return (uint32_t)data.size(); }
  ROSCPP_DEPRECATED void set_data_size(uint32_t size) { data.resize((size_t)size); }
  ROSCPP_DEPRECATED void get_data_vec(std::vector<float, typename ContainerAllocator::template rebind<float>::other > & vec) const { vec = this->data; }
  ROSCPP_DEPRECATED void set_data_vec(const std::vector<float, typename ContainerAllocator::template rebind<float>::other > & vec) { this->data = vec; }
private:
  static const char* __s_getDataType_() { return "gradient_planner/GPCostmapM"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "5fb9da7eea71c83e315b2e5130c03354"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
string name\n\
int32 rows\n\
int32 cols\n\
float32[] data\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, name);
    ros::serialization::serialize(stream, rows);
    ros::serialization::serialize(stream, cols);
    ros::serialization::serialize(stream, data);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, name);
    ros::serialization::deserialize(stream, rows);
    ros::serialization::deserialize(stream, cols);
    ros::serialization::deserialize(stream, data);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(name);
    size += ros::serialization::serializationLength(rows);
    size += ros::serialization::serializationLength(cols);
    size += ros::serialization::serializationLength(data);
    return size;
  }

  typedef boost::shared_ptr< ::gradient_planner::GPCostmapM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gradient_planner::GPCostmapM_<ContainerAllocator>  const> ConstPtr;
}; // struct GPCostmapM
typedef  ::gradient_planner::GPCostmapM_<std::allocator<void> > GPCostmapM;

typedef boost::shared_ptr< ::gradient_planner::GPCostmapM> GPCostmapMPtr;
typedef boost::shared_ptr< ::gradient_planner::GPCostmapM const> GPCostmapMConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::gradient_planner::GPCostmapM_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::gradient_planner::GPCostmapM_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace gradient_planner

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::gradient_planner::GPCostmapM_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5fb9da7eea71c83e315b2e5130c03354";
  }

  static const char* value(const  ::gradient_planner::GPCostmapM_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5fb9da7eea71c83eULL;
  static const uint64_t static_value2 = 0x315b2e5130c03354ULL;
};

template<class ContainerAllocator>
struct DataType< ::gradient_planner::GPCostmapM_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gradient_planner/GPCostmapM";
  }

  static const char* value(const  ::gradient_planner::GPCostmapM_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gradient_planner::GPCostmapM_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
string name\n\
int32 rows\n\
int32 cols\n\
float32[] data\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::gradient_planner::GPCostmapM_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::gradient_planner::GPCostmapM_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gradient_planner::GPCostmapM_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.name);
    stream.next(m.rows);
    stream.next(m.cols);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GPCostmapM_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gradient_planner::GPCostmapM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::gradient_planner::GPCostmapM_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::roslib::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "rows: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rows);
    s << indent << "cols: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cols);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // GRADIENT_PLANNER_MESSAGE_GPCOSTMAPM_H

