/* Auto-generated by genmsg_cpp for file /home/matt/myrospackages/robotunicorn225b/project2/gradient_planner/msg/GPPath.msg */
#ifndef GRADIENT_PLANNER_MESSAGE_GPPATH_H
#define GRADIENT_PLANNER_MESSAGE_GPPATH_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "roslib/Header.h"

namespace gradient_planner
{
template <class ContainerAllocator>
struct GPPath_ : public ros::Message
{
  typedef GPPath_<ContainerAllocator> Type;

  GPPath_()
  : header()
  , length(0)
  , x()
  , y()
  {
  }

  GPPath_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , length(0)
  , x(_alloc)
  , y(_alloc)
  {
  }

  typedef  ::roslib::Header_<ContainerAllocator>  _header_type;
   ::roslib::Header_<ContainerAllocator>  header;

  typedef int32_t _length_type;
  int32_t length;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  x;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  y;


  ROSCPP_DEPRECATED uint32_t get_x_size() const { return (uint32_t)x.size(); }
  ROSCPP_DEPRECATED void set_x_size(uint32_t size) { x.resize((size_t)size); }
  ROSCPP_DEPRECATED void get_x_vec(std::vector<float, typename ContainerAllocator::template rebind<float>::other > & vec) const { vec = this->x; }
  ROSCPP_DEPRECATED void set_x_vec(const std::vector<float, typename ContainerAllocator::template rebind<float>::other > & vec) { this->x = vec; }
  ROSCPP_DEPRECATED uint32_t get_y_size() const { return (uint32_t)y.size(); }
  ROSCPP_DEPRECATED void set_y_size(uint32_t size) { y.resize((size_t)size); }
  ROSCPP_DEPRECATED void get_y_vec(std::vector<float, typename ContainerAllocator::template rebind<float>::other > & vec) const { vec = this->y; }
  ROSCPP_DEPRECATED void set_y_vec(const std::vector<float, typename ContainerAllocator::template rebind<float>::other > & vec) { this->y = vec; }
private:
  static const char* __s_getDataType_() { return "gradient_planner/GPPath"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0c497d9c4f459ad6e83d5642da79a4c1"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
int32 length\n\
float32[] x\n\
float32[] y\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, length);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, length);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(length);
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    return size;
  }

  typedef boost::shared_ptr< ::gradient_planner::GPPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gradient_planner::GPPath_<ContainerAllocator>  const> ConstPtr;
}; // struct GPPath
typedef  ::gradient_planner::GPPath_<std::allocator<void> > GPPath;

typedef boost::shared_ptr< ::gradient_planner::GPPath> GPPathPtr;
typedef boost::shared_ptr< ::gradient_planner::GPPath const> GPPathConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::gradient_planner::GPPath_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::gradient_planner::GPPath_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace gradient_planner

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::gradient_planner::GPPath_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0c497d9c4f459ad6e83d5642da79a4c1";
  }

  static const char* value(const  ::gradient_planner::GPPath_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0c497d9c4f459ad6ULL;
  static const uint64_t static_value2 = 0xe83d5642da79a4c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::gradient_planner::GPPath_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gradient_planner/GPPath";
  }

  static const char* value(const  ::gradient_planner::GPPath_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gradient_planner::GPPath_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 length\n\
float32[] x\n\
float32[] y\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::gradient_planner::GPPath_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::gradient_planner::GPPath_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gradient_planner::GPPath_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.length);
    stream.next(m.x);
    stream.next(m.y);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GPPath_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gradient_planner::GPPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::gradient_planner::GPPath_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::roslib::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.length);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // GRADIENT_PLANNER_MESSAGE_GPPATH_H

